name: Build iOS IPA
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pods
        run: pod install
      - name: Build Archive
        run: |
          xcodebuild -workspace "The white team.xcworkspace" -scheme "The white team" -sdk iphoneos -configuration Release archive -archivePath $PWD/build/App.xcarchive
          xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build -allowProvisioningUpdates
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-ipa
          path: build/*.ipa
